name: Auto Update Calendar

on:
  schedule:
    - cron: "30 * * * *"
  push:

jobs:
  execute:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v4.2.0
        with:
          # Version range or exact version of Python or PyPy to use, using SemVer's version range syntax. Reads from .python-version if unset.
          python-version: '3.10' # optional

      - name: Poetry Install
        # You may pin to the exact commit or the version.
        # uses: knowsuchagency/poetry-install@7ed80d49910319d3e14ac262a5c81f681de48de0
        uses: knowsuchagency/poetry-install@v2
        with:
          # Have poetry create a virtualenv for the project on installation.
          create-virtualenv: false # optional, default is false
      - name: Run
        run: |
          python main.py
