name: Auto Update Calendar

on:
  schedule:
    - cron: "30 * * * *"
  push:

jobs:
  execute:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Poetry Install
        # You may pin to the exact commit or the version.
        # uses: knowsuchagency/poetry-install@7ed80d49910319d3e14ac262a5c81f681de48de0
        uses: knowsuchagency/poetry-install@v2
        with:
          # Have poetry create a virtualenv for the project on installation.
          create-virtualenv: true # optional, default is false
      - name: Run
        run: |
          poetry run main.py
